// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCredentials() {
  return window['go']['main']['App']['ClearCredentials']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetFriendList() {
  return window['go']['main']['App']['GetFriendList']();
}

export function GetGroupHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGroupHistory'](arg1, arg2, arg3);
}

export function GetHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2, arg3);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function LoadCredentials() {
  return window['go']['main']['App']['LoadCredentials']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function SaveCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2, arg3);
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function SendGroupMessage(arg1, arg2) {
  return window['go']['main']['App']['SendGroupMessage'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
