// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetFriendList():Promise<void>;

export function GetGroupHistory(arg1:string,arg2:number,arg3:number):Promise<void>;

export function GetHistory(arg1:number,arg2:number,arg3:number):Promise<void>;

export function GetSessions():Promise<void>;

export function Login(arg1:number,arg2:string):Promise<void>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function SendGroupMessage(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:number,arg2:string):Promise<void>;
